# Generated by Django 4.2.7 on 2023-12-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0002_alter_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
    ]
