# Generated by Django 4.2.7 on 2023-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0004_alter_query_tiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='saved',
            new_name='is_saved',
        ),
        migrations.AddField(
            model_name='tile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
