# Generated by Django 4.2.7 on 2023-12-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0005_rename_saved_tile_is_saved_tile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='poster_db_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
