# Generated by Django 4.2.7 on 2023-12-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0006_tile_poster_db_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='poster_db_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
