# Generated by Django 4.2.7 on 2023-12-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0007_alter_tile_poster_db_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
